export {
  type TabsActivationMode,
  type TabsChangeDetails,
  type TabsListOptions,
  TabsListRenderable,
  type TabsOrientation,
  type TabsPanelOptions,
  TabsPanelRenderable,
  type TabsPanelState,
  type TabsRootOptions,
  TabsRootRenderable,
  type TabsState,
  TabsStore,
  type TabsStoreOptions,
  type TabsTabOptions,
  TabsTabRenderable,
  type TabsTabState,
  type TabsValueChangeHandler,
} from "./primitive";
