export {
  type CollapsibleOpenChangeDetails,
  type CollapsibleOpenChangeHandler,
  type CollapsiblePanelOptions,
  CollapsiblePanelRenderable,
  type CollapsiblePanelState,
  type CollapsibleRootOptions,
  CollapsibleRootRenderable,
  type CollapsibleState,
  CollapsibleStore,
  type CollapsibleStoreOptions,
  type CollapsibleTriggerOptions,
  CollapsibleTriggerRenderable,
  type CollapsibleTriggerState,
} from "./primitive";
